### ISSUE TITLE
[Question]Rate limit for host yt3.googleusercontent.com

### ISSUE THREAD

**Issue by 11Tuvork28** [TeamPiped/piped-proxy#20]
I'm running this proxy for use with invidious, seems like that there's a rate for channel banners?
E.g [this](https://proxy.invidio.xamh.de/LBNNx-r4KhH2D1RdFQBvHAgsQZeAX4Qly0FUqKwr4X46qkCweFoVFQ5kl6P-nkEgxKJRp02gjw=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rw?host=yt3.googleusercontent.com) banner or really any channel for that matter, sometimes it works but most of the time it won't.
How do you work around this limitation, with your proxy instance(s)?

**Comment by FireMasterK** [comment]
I'm sorry, I don't understand/know what rate limit you're talking about. The image loads fine for me.

**Comment by 11Tuvork28** [comment]
All good, I think I know why it mysteriously fails sometimes.
Seems that invidious sometimes produces urls that don't work with the proxy.
Closing because of user error.
